const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSettings: (s) => ipcRenderer.invoke('save-settings', s),
  getPresets: () => ipcRenderer.invoke('get-presets'),
  savePreset: (preset) => ipcRenderer.invoke('save-preset', preset),
  deletePreset: (label) => ipcRenderer.invoke('delete-preset', label),
  reorderPresets: (presets) => ipcRenderer.invoke('reorder-presets', presets),
  getToneModes: () => ipcRenderer.invoke('get-tone-modes'),
  getIntentModes: () => ipcRenderer.invoke('get-intent-modes'),
  addToneMode: () => ipcRenderer.invoke('add-tone-mode'),
  renameToneMode: (from, to) => ipcRenderer.invoke('rename-tone-mode', { from, to }),
  deleteToneMode: (name) => ipcRenderer.invoke('delete-tone-mode', name),
  reorderToneModes: (orderedNames) => ipcRenderer.invoke('reorder-tone-modes', orderedNames),
  sendToClaude: (text, prompt, isEmail, presetLabel) => ipcRenderer.invoke('claude-request', { text, prompt, isEmail, presetLabel }),
  hideWindow: () => ipcRenderer.send('hide-window'),
  minimizeWindow: () => ipcRenderer.send('minimize-window'),
  toggleMaximizeWindow: () => ipcRenderer.send('toggle-maximize-window'),
  openSettings: () => ipcRenderer.send('open-settings'),
  closeSettingsWindow: () => ipcRenderer.send('close-settings'),
  openAccessibilitySettings: () => ipcRenderer.send('open-accessibility-settings'),
  openAutomationSettings: () => ipcRenderer.send('open-automation-settings'),
  checkPermissions: () => ipcRenderer.invoke('check-permissions'),
  getAppName: () => ipcRenderer.invoke('get-app-name'),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  copyToClipboard: (t) => ipcRenderer.send('copy-to-clipboard', t),
  sendFeedback: (body) => ipcRenderer.invoke('send-feedback', body),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  suspendShortcutRecording: () => ipcRenderer.send('suspend-shortcut-recording'),
  resumeShortcutRecording: () => ipcRenderer.send('resume-shortcut-recording'),
  onSelectedText: (cb) => ipcRenderer.on('selected-text', (e, t) => cb(t)),
  onPresetsUpdated: (cb) => ipcRenderer.on('presets-updated', (e, presets) => cb(presets)),
  onModesUpdated: (cb) => ipcRenderer.on('modes-updated', (e, modes) => cb(modes)),
  onShortcutConflictStatus: (cb) => ipcRenderer.on('shortcut-conflict-status', (e, conflict) => cb(conflict)),
  onMotherLanguageStatus: (cb) => ipcRenderer.on('mother-language-status', (e, lang) => cb(lang)),
  onAppLanguageStatus: (cb) => ipcRenderer.on('app-language-status', (e, lang) => cb(lang))
});
